version: 2.1
executorType: machine
jobs:
  build:
#    machine: true
    docker:
      - image: circleci/redis:latest
    steps:
      - checkout
      - restore_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run: cd course-mw/enrolment-actor && mvn scoverage:report
      - run: cd service && mvn play2:dist
      - save_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2

      - run:
          name: sonar
          command: |
            srcBranch=$(curl -s https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls/$CIRCLE_PR_NUMBER | jq .head.ref -r)
            tarBranch=$(curl -s https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls/$CIRCLE_PR_NUMBER | jq .base.ref -r)
            mvn verify -DskipTests=true sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-course-service -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.pullrequest.branch=$srcbranch -Dsonar.pullrequest.key=$CIRCLE_PR_NUMBER -Dsonar.pullrequest.base=$tarbranch -Dsonar.scala.coverage.reportPaths=/home/circleci/project/course-mw/enrolment-actor/target/scoverage.xml
      
workflows:
  version: 2.1
  workflow:
    jobs:
      - build
